---------------------------------------------------------------------------------------
-- Name - insertMapBlank.sql
-- Author - Evan Wu
-- Date Last Modified - 11-17-2019
-- Description - SQL File that contains query to insert into both MAPS_DMAPS_META and MAPS_DMAP_LISTS.
-- 				This version is empty, so that user input can be done later.
---------------------------------------------------------------------------------------

-- The following variable statements need input from the user.
-- map_name
-- degree
-- start_year

-- The following variables should be automatically obtained.
-- institute_id - This is dependant on the user's account. 17 is the value for Queens college.
-- map_id - Set to automatically increment on input by 1.
-- active_status - By default, any inserted map is active.
-- submit_id/last_update - Should be automatically obtained from credentials.
-- submit_time/last - Uses current server time stamp.

SET @map_name = '';
SET @degree = '';
SET @start_year = '';
SET @active_status = 'A';
SET @institute_id = '17';
SET @submit_id = '';
SET @submit_time = CURRENT_TIMESTAMP();
SET @last_update = @submit_id;
SET @last_update_time = @submit_time;

INSERT INTO MAPS_DMAPS_META (map_name, degree, start_year, institute_id, submit_id, submit_time, last_update, last_update_time)
VALUES (@map_name, @degree, @start_year, @institute_id, submit_id, @submit_time, @last_update, @last_update_time);

-- MAP_ID is generated by the previous insert statement.
-- For each Semester/Class variable below, it would have to come from user input. 

SET @map_id = last_insert_id();
SET @sem1_class1 = '';
SET @sem1_class2 = '';
SET @sem1_class3 = '';
SET @sem1_class4 = '';
SET @sem1_class5 = '';
SET @sem1_class6 = '';
SET @sem1_class7 = '';
SET @sem2_class1 = '';
SET @sem2_class2 = '';
SET @sem2_class3 = '';
SET @sem2_class4 = '';
SET @sem2_class5 = '';
SET @sem2_class6 = '';
SET @sem2_class7 = '';
SET @sem3_class1 = '';
SET @sem3_class2 = '';
SET @sem3_class3 = '';
SET @sem3_class4 = '';
SET @sem3_class5 = '';
SET @sem3_class6 = '';
SET @sem3_class7 = '';
SET @sem3_class1 = '';
SET @sem3_class2 = '';
SET @sem3_class3 = '';
SET @sem3_class4 = '';
SET @sem3_class5 = '';
SET @sem3_class6 = '';
SET @sem3_class7 = '';
SET @sem4_class1 = '';
SET @sem4_class2 = '';
SET @sem4_class3 = '';
SET @sem4_class4 = '';
SET @sem4_class5 = '';
SET @sem4_class6 = '';
SET @sem4_class7 = '';
SET @sem5_class1 = '';
SET @sem5_class2 = '';
SET @sem5_class3 = '';
SET @sem5_class4 = '';
SET @sem5_class5 = '';
SET @sem5_class6 = '';
SET @sem5_class7 = '';
SET @sem6_class1 = '';
SET @sem6_class2 = '';
SET @sem6_class3 = '';
SET @sem6_class4 = '';
SET @sem6_class5 = '';
SET @sem6_class6 = '';
SET @sem6_class7 = '';
SET @sem7_class1 = '';
SET @sem7_class2 = '';
SET @sem7_class3 = '';
SET @sem7_class4 = '';
SET @sem7_class5 = '';
SET @sem7_class6 = '';
SET @sem7_class7 = '';
SET @sem7_class1 = '';
SET @sem7_class2 = '';
SET @sem7_class3 = '';
SET @sem7_class4 = '';
SET @sem7_class5 = '';
SET @sem7_class6 = '';
SET @sem7_class7 = '';
SET @sem8_class1 = '';
SET @sem8_class2 = '';
SET @sem8_class3 = '';
SET @sem8_class4 = '';
SET @sem8_class5 = '';
SET @sem8_class6 = '';
SET @sem8_class7 = '';

INSERT INTO MAPS_DMAPS_LISTS
VALUES (@map_id, '1', @sem1_class1, @sem1_class2, @sem1_class3, @sem1_class4, @sem1_class5, @sem1_class6, @sem1_class7),
(@map_id, '2', @sem2_class1, @sem2_class2, @sem2_class3, @sem2_class4, @sem2_class5, @sem2_class6, @sem2_class7),
(@map_id, '3', @sem3_class1, @sem3_class2, @sem3_class3, @sem3_class4, @sem3_class5, @sem3_class6, @sem3_class7),
(@map_id, '4', @sem4_class1, @sem4_class2, @sem4_class3, @sem4_class4, @sem4_class5, @sem4_class6, @sem4_class7),
(@map_id, '5', @sem5_class1, @sem5_class2, @sem5_class3, @sem5_class4, @sem5_class5, @sem5_class6, @sem5_class7),
(@map_id, '6', @sem6_class1, @sem6_class2, @sem6_class3, @sem6_class4, @sem6_class5, @sem6_class6, @sem6_class7),
(@map_id, '7', @sem7_class1, @sem7_class2, @sem7_class3, @sem7_class4, @sem7_class5, @sem7_class6, @sem7_class7),
(@map_id, '8', @sem8_class1, @sem8_class2, @sem8_class3, @sem8_class4, @sem8_class5, @sem8_class6, @sem8_class7)